Repository kom-senapati/TerminalFolio, pull requests merged in 2025-03, with the labels that each got.

#11 Created user.json
  README.md
  src/config/user.json
Labels: apertre2.0, Easy

#14 Load user.json in Script
  script.js
  styles.css
Labels: apertre2.0, Medium

#19 Create SECURITY.md
  SECURITY.md
Labels: Doc, apertre2.0

#20 Create Code of Conduct.md
  Code of Conduct.md
Labels: Doc, apertre2.0

#25 Matrix Effect
  README.md
  commands.json
  script.js
  styles.css
Labels: apertre2.0, Hard

#40 Created config.json with required details
  src/config/config.json
Labels: apertre2.0, Easy

#42 History
  script.js
Labels: apertre2.0, Medium

#44 commands.json added
  src/config/commands.json
Labels: apertre2.0, Easy

#48 Rps
  README.md
  commands.json
  script.js
Labels: apertre2.0, Medium

#46 input field responsiveness
  styles.css
Labels: apertre2.0, Easy

#52 Ubuntu Theme
  script.js
Labels: apertre2.0, Medium

#53 Header
  index.html
  styles.css
Labels: apertre2.0, Hard

#47 Added special commands
  .vscode/settings.json
  commands.json
  script.js
Labels: apertre2.0, Medium

#58 Added loading state for api based commands
  index.html
  script.js
  styles.css
Labels: apertre2.0, Medium

#60 File Structure Implemented in the project
  commands.json
  index.html
  src/config/user.json
  src/js/commands.js
  src/js/config.js
  src/js/script.js
  src/js/user.js
  src/styles/styles.css
Labels: apertre2.0, Hard

#61 updated readme with src/config values
  README.md
  commands.json
Labels: Doc, apertre2.0

#63 Logo
  README.md
  index.html
  terminal_folio.png
  terminal_folio.svg
Labels: apertre2.0, Easy
